---
# SNO requires to match master role
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-master-enable-8021q
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8,8021q
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/8021q-load.conf
