---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/ran-du-sno: telco-gitops

bases:
  # Use ran-du as base
  - ../ran-du

## NOTE: This needs to be fix

# resources:
#   - 01-mcp.yaml

# patches:
# - 01-patch-mcp-master.yaml
