apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
        certificate: |-
          -----BEGIN CERTIFICATE-----
          MIIFYDCCBEigAwIBAgISBMmHMEwKs7/nzOh1sEQsp+DHMA0GCSqGSIb3DQEBCwUA
          MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
          EwJSMzAeFw0yMTEwMTUwODMyMzhaFw0yMjAxMTMwODMyMzdaMCcxJTAjBgNVBAMT
          HGFwaS5haS1ibS0wMS5jbHVzdGVyc2hpcC5jb20wggEiMA0GCSqGSIb3DQEBAQUA
          A4IBDwAwggEKAoIBAQDmfIvYWFNYy1EIg4G407XCAhZGqovpssJvfC/qPVX8rt/k
          t5BGUBMtjq3U3dLEORNjJ+tUV0Zow8Nc5WkiZHwiSpOOpWtXpsGwiVn72nJQS+z2
          xrfAMXPOyettDWZW7p8pl6nrgmAj5axumtwG7wqpoMoJw3s2rnWjsL+m4w/hPeYu
          DvGmyAPN2W747ayrH2Y1phyUZfXEPDRSbF0gebIIriuhCxPrY3MIHBUITzECZr2J
          OK2svUx9KSFniHUJu+XiS63JE5ig8YMGr9kfrBnS4j/Hxj4b8MH8yyCCSWSq0knQ
          FF/A0Kv1DkXAFclZ4CRy5GoiGktO1+hFf6b8+2WDAgMBAAGjggJ5MIICdTAOBgNV
          HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
          EwEB/wQCMAAwHQYDVR0OBBYEFGCx34GFrMFcECg44fyFh3m+Fdi0MB8GA1UdIwQY
          MBaAFBQusxe3WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEF
          BQcwAYYVaHR0cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8v
          cjMuaS5sZW5jci5vcmcvMEgGA1UdEQRBMD+CHyouYXBwcy5haS1ibS0wMS5jbHVz
          dGVyc2hpcC5jb22CHGFwaS5haS1ibS0wMS5jbHVzdGVyc2hpcC5jb20wTAYDVR0g
          BEUwQzAIBgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0
          cDovL2Nwcy5sZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEA
          dgDfpV6raIJPH2yt7rhfTj5a6s2iEqRqXo47EsAgRFwqcwAAAXyDS9dxAAAEAwBH
          MEUCIQCDO8jXozOXtQnZmExkOzntcReXW1NQmuAkvftg7K+ScAIgdWsVwaRi2qZZ
          T2Isb6ypHH0VTgIjz2pZqjROwuQKJAYAdwApeb7wnjk5IfBWc59jpXflvld9nGAK
          +PlNXSZcJV3HhAAAAXyDS9dvAAAEAwBIMEYCIQDaGMYJFftVViTiDOgEFCRsTZXz
          X1epXjndDyxrkgn6IAIhAKh2Jwb3heFJGlBtiI1GfiuvEd1S/vu7izOZzzx0Z5RN
          MA0GCSqGSIb3DQEBCwUAA4IBAQBOQEHos3xsJ3woBoOqqHUp2qk4y7Pzj+WHaabO
          1d4oLzcogWVFRC1OmIbYUHt5WKyDPhNhymY65/JvrIB6yQOvdtRnRv7Tun8/qC0B
          rLfZO3heWpW8o9RpgNy4dhYmD0hbhaepQbfJKAtK3T1kZTFJulu+JCbVphLTE9Q6
          VWWixVexOpjYglmLnbAqwfA1IDca9bmFPiB0ohTgmxnXa5LwR7xbJtEi8qECOAJV
          3I/ZWRqxTtXH4aQMo4JvKcd3/PT466vJ/bTHlpQBkPnKLa1V40CLJGHbfh/gEoP+
          EjRYp0acHKj5EGLaW55F/RORB9AhwLWuO8SxN8CgSxdOCTRp
          -----END CERTIFICATE-----

          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----

          -----BEGIN CERTIFICATE-----
          MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
          MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
          DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
          AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
          ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
          wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
          LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
          4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
          bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
          sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
          Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
          FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
          SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
          PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
          TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
          SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
          c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
          +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
          ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
          b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
          U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
          MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
          5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
          9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
          WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
          he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
          Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
          -----END CERTIFICATE-----
        key: |-
          -----BEGIN RSA PRIVATE KEY-----
          MIIEpQIBAAKCAQEA5nyL2FhTWMtRCIOBuNO1wgIWRqqL6bLCb3wv6j1V/K7f5LeQ
          RlATLY6t1N3SxDkTYyfrVFdGaMPDXOVpImR8IkqTjqVrV6bBsIlZ+9pyUEvs9sa3
          wDFzzsnrbQ1mVu6fKZep64JgI+WsbprcBu8KqaDKCcN7Nq51o7C/puMP4T3mLg7x
          psgDzdlu+O2sqx9mNaYclGX1xDw0UmxdIHmyCK4roQsT62NzCBwVCE8xAma9iTit
          rL1MfSkhZ4h1Cbvl4kutyROYoPGDBq/ZH6wZ0uI/x8Y+G/DB/MsggklkqtJJ0BRf
          wNCr9Q5FwBXJWeAkcuRqIhpLTtfoRX+m/PtlgwIDAQABAoIBAQCvZd5CQE0FCIxd
          Dz6bubjasB3lnwmkSZ3/myEXf5+9EBNgCXUonO1LQQX2NOyc2NZxIcLLRzNUrI0y
          V36fZpq0uc36wtWiOUuynYO1znIpuu3UijrxbnCz0CNxtL3JsAO9ciYkC+4/wxtq
          fDyupiCWH79AmNteLHtnmyztwmOmQrOyM/uGrpcnZHdcpxplT9pNuVtKXPXNyAea
          /CiymuEFydDk/j3JWbO5tbROeOugHbqmw//IxONAvufZEWodKhP5jt0BwMW2oGU6
          uQ8y9ahiOUcO+MjJDUefD+2vKg7Qp4deh2Qzes+G18qk9bEthqdLF2uXhbrjzSKg
          gRwKWjZhAoGBAPz1cws3Tqz6Dt7zTBOAP7RX3MEsG8AwLS1UwCleMPe2FtntQBrY
          21em6eEL9jeYxQn8q/LWwiwnS8RE7NtPAvci27M/NlQkmXKRlPmyLh/IUQ2BEQTQ
          +WWLezAIfKHnV26Syu/vhXu57h7b9SzPYMMPeXDOePYIN/ZFcWuYMY9zAoGBAOlB
          7qa3M9QS0mBXMV07ZAGF4+Ef3IaS6jYPkAC+LLlQKKr6IqQnTCR1ORduAyt+2Dxn
          TmLh6B0JaEQSGT7+rX2HvqpNBLe4alaxM3sfdyx2tjWTUb3cCSym/FF+rsTAZfhO
          uEqQCD5IKCBL49iLi6t63KbdXlWnKrWsaLGhgC2xAoGAaiPniN5FIemu0bgOxOP8
          VwTC+T8zybmtSycTlogSTe5WukyFqH4z0xyTaD2nq35rtxwRXkzknrhCX3F4XTFT
          EjXLL/QnLLlKtbsGYpt0JRvdfqgYZwf0jbowD2CQQzMaCaiIhJLhVKAYnVQ4FPxT
          IqXclAvez4V1Td2nkLkEmqcCgYEAkQaQRhGD5Ohq6sFrjMb/T78aRv9TUkyH2GLm
          qr+S+QjwsBVjcmKIgeZsP7gDuohcE3o7j1lbwqn1rNT/413fKjw6/JF0THIZk5sL
          IhMXOor4kOjumrfy8FNGb7jvGp9xBuiSxrE0ntyoLiRhHmLszQpPpGPgYirUcC4o
          zcBW/JECgYEAvPGCNxUWHztct7VkdCJxPgjSv8DMXm8aWL66v1aErfN1hmy39mOQ
          0r9GKKvNZG47Yn0GcImjmNQPmEIYq72ARfsSgXEU7yDRGaWNypbhdup+794UZPoe
          QpQDWo1NPfoI1ADkO49kf627aSie/WMv2lvz9WCYrKuEIYQTebrMLMY=
          -----END RSA PRIVATE KEY-----
