---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-openshift-gitops-argocd-application-controller-rhacm
rules:
- apiGroups:
  - operator.open-cluster-management.io
  - hive.openshift.io
  - agent-install.openshift.io
  - ocs.openshift.io
  - odf.openshift.io
  - local.storage.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
  name: openshift-gitops-openshift-gitops-argocd-application-controller-rhacm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-gitops-openshift-gitops-argocd-application-controller-rhacm
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
