# RM 20
---
apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: ran-du-profile0
spec:
  cpu:
    isolated: "4-31"
    reserved: "0-3"
  net:
    userLevelNetworking: true
    devices:
    - interfaceName: "eno8*"
    - interfaceName: "ens3*"
    - interfaceName: "ens4*"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 16
      node: 0
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: false
  nodeSelector:
    node-role.kubernetes.io/ran-du-oe20: ""
