apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: merge-all-kubeletconfig-bz1967911
spec:
  kubeletConfig:
    apiVersion: kubelet.config.k8s.io/v1beta1
    allowedUnsafeSysctls:
    - kernel.msg*
    - net.core.somaxconn
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
    authentication:
      anonymous: {}
      webhook:
        cacheTTL: 0s
      x509: {}
    authorization:
      webhook:
        cacheAuthorizedTTL: 0s
        cacheUnauthorizedTTL: 0s
    cpuManagerPolicy: static
    cpuManagerReconcilePeriod: 5s
    evictionPressureTransitionPeriod: 0s
    fileCheckFrequency: 0s
    httpCheckFrequency: 0s
    imageMinimumGCAge: 0s
    kind: KubeletConfiguration
    kubeReserved:
      cpu: 1000m
      memory: 500Mi
    logging: {}
    maxPods: 500
    nodeStatusReportFrequency: 0s
    nodeStatusUpdateFrequency: 0s
    podsPerCore: 0
    podPidsLimit: 4096
    reservedSystemCPUs: 0-3
    runtimeRequestTimeout: 0s
    shutdownGracePeriod: 0s
    shutdownGracePeriodCriticalPods: 0s
    streamingConnectionIdleTimeout: 0s
    syncFrequency: 0s
    systemReserved:
      cpu: 1000m
      memory: 500Mi
    topologyManagerPolicy: best-effort
    volumeStatsAggPeriod: 0s
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ""
