---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openshift-gitops-argocd-application-controller-for-operators
  namespace: openshift-gitops
rules:
- apiGroups:
  - local.storage.openshift.io
  resources:
  - localvolumes
  verbs:
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-gitops-argocd-application-controller-for-operators
  namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-argocd-application-controller-for-operators
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
