---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    #
    # Namespace, OperatorGroup and Subscription resources exist on OpenShift.
    # So everything can be applied in the initial wave
    #
    argocd.argoproj.io/sync-wave: "5"
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-local-storage
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: openshift-local-storage
  namespace: openshift-local-storage
spec:
  targetNamespaces:
    - openshift-local-storage
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: openshift-local-storage-operator
  namespace: openshift-local-storage
spec:
  channel: "4.9"
  installPlanApproval: Automatic
  name: local-storage-operator
  # Modify source name of the catalogsource for isolated network deployments
  source: redhat-operators
  sourceNamespace: openshift-marketplace
