---
apiVersion: local.storage.openshift.io/v1
kind: LocalVolume
metadata:
  name: local-disks
  namespace: openshift-local-storage 
spec:
  managementState: Managed
  nodeSelector: 
    nodeSelectorTerms:
    - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: Exists
  storageClassDevices:
    - storageClassName: "localblock-sc" 
      volumeMode: Block  
      devicePaths: 
        - /dev/sdb
