---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-ens1f0-sriov-node-network-policy.yaml
- 02-ens4f1-sriov-node-network-policy.yaml
# - 01-ens1f1-sriov-node-network-policy.yaml
# - 02-ens9f0-sriov-node-network-policy.yaml
