---
apiVersion: config.openshift.io/v1
kind: Scheduler
metadata:
  annotations:
      argocd.argoproj.io/sync-wave: "10"
  name: cluster
spec:
  mastersSchedulable: true
status: {}
---
#
# Wait for multiclusterhub instance to be ready to continue
#
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: storage-label-job
  # generateName: csv-wait-job-
  namespace: openshift-gitops
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              echo "ArgoCD PreSync Hook"
              oc label nodes $(oc get nodes -l node-role.kubernetes.io/master='' -o jsonpath='{..metadata.name}') cluster.ocs.openshift.io/openshift-storage=''
              echo "Labelling done! Hooray!"
          imagePullPolicy: IfNotPresent
          name: storage-label-job
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: cli-job-sa
      serviceAccountName: cli-job-sa
      terminationGracePeriodSeconds: 30
