---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: openshift-gitops
  namespace: openshift-gitops
spec:
  server:
    route:
      enabled: true
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: reencrypt
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-openshift-gitops-argocd-application-controller-rhacm
rules:
- apiGroups:
  - operator.open-cluster-management.io
  - hive.openshift.io
  - agent-install.openshift.io
  resources:
  - '*'
  verbs:
  - '*'
