---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Prune=true
  argocd.argoproj.io/sync-wave: "55"

resources:
- 01-ptp-ran-du.yaml
# - 01-ptp-slave-flexran.yaml
