
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  telco-gitops/cluster-type: sno

bases:
  #####################################################
  # Operators for Node Features Discovery
  #####################################################
  # Operator
  - ../../base/operators/openshift-nfd
  # Config
  - ../../base/configs/openshift-nfd
