---
apiVersion: config.openshift.io/v1
kind: OperatorHub
metadata:
  name: cluster
spec:
  disableAllDefaultSources: true
---
#
# Change registry and version appropriately
#
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: mirrored-rh-operator-catalog
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: hubcluster-registry.apps.mgmt.espoo.nsn-rdnet.net/operators/redhat-operator-index:v4.9
  displayName: Nokia Lab
  publisher: nokialab
  updateStrategy:
    registryPoll:
      interval: 30m
