apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  storageDeviceSets:
  - name: ocs-deviceset
    count: 3
    dataPVCTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1
        storageClassName: localblock-sc
        volumeMode: Block
    placement: {}
    portable: false
