apiVersion: odf.openshift.io/v1alpha1
kind: StorageSystem
metadata:
  generation: 1
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
spec:
  kind: storagecluster.ocs.openshift.io/v1
  name: ocs-storagecluster
  namespace: openshift-storage
