#
# Adjust this secret to contains a real base64 encoded htpasswd file with strong passwords.
#
apiVersion: v1
data:
  htpasswd: bm9raWFhZG1pbjokYXByMSR2RjQxVk1WMyRRTXhybFZJOWRpeExYdVpVSXBneEQvCg==
kind: Secret
metadata:
  annotations:
      argocd.argoproj.io/sync-options: Prune=true
  creationTimestamp: null
  name: idp-htpass-secret
  namespace: openshift-config
