apiVersion: v1
data:
  htpasswd: dGVsY29hZG1pbjokMnkkMDUkOG1vcC5kRDc3cFV6UFBzaFBnWDNvLkhTMENXZ25VbDJjcUIuTzNXejNJc29uUTB6L1oxYi4Kb3BlcmF0aW9uczokMnkkMDUkSUpxTkZjNElmMldQWmFYSHpDZFpSdVhsM1hlQ1diV2NnUFlmM25JOG5RbU4wbWJ0clVEeDIKdmVuZG9yY25mMTokMnkkMDUkcEdKb1cyLnFjZndBeVVXMGFFcW5jZWJkaGdnc2pGS2R6ZkVFeDFjSWE1Nm1Ja1c5bFQ1b0cKdmVuZG9yY25mMjokMnkkMDUkQU9XcGpmVzZqTS9JMmkzeUtUMng3T0szMkxGN3J5eEJQblRwck1uSXUyT1BvSlBFNndkeFcKdmVuZG9yY25mMzokMnkkMDUkYzd4bVRPZTVrbDZTOXVlaVRlZ1djT01MQnYxNGFCUk5KZFFXWUhoYTZFdzJhU1g0eTRmMGEK
kind: Secret
metadata:
  creationTimestamp: null
  name: idp-htpass-secret
  namespace: openshift-config
