---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata: 
  labels:
    custom-kubelet: max-pods-500
    machineconfiguration.openshift.io/role: ran-du
  name: ran-du
spec:
  machineConfigSelector:
    matchExpressions:
      - {
          key: machineconfiguration.openshift.io/role,
          operator: In,
          values: [worker, ran, ran-du]
        }
  paused: false
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/ran-du: ""

# oc patch mcp ran-du -p '{"spec": {"paused": true}}'