---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
# Deploy RHACM
- ../../base/operators/advanced-cluster-management/

## NOTE: This needs to be fix

# resources:
#   - 01-mcp.yaml

# patches:
# - 01-patch-mcp-master.yaml
